### ISSUE TITLE
How to solve the error when installing midi-ddsp? 

### ISSUE THREAD

**Issue by Megan8821** [magenta/midi-ddsp#57]
Hi, I am new in installing model, and I got some problems in here. Does anyone how to solve the error of ```error: subprocess-exited-with
-error``` and ```error: metadata-generation-failed``` in the terminal?

**Comment by lukewys** [comment]
Hi! Could you please describe how you installed the package or what command you entered?

**Comment by Megan8821** [comment]
I type pip3 install midi-ddsp, and the other packages(e.g. crep, tensorflow) it installed successfully. Thanks

**Comment by Megan8821** [comment]
I solved it, but I have another issue.

**Comment by lukewys** [comment]
Hi Megan, I saw you opened a new issue for the new problem. I am closing this issue if you do not have further problems with training the model. :)

**Comment by Megan8821** [comment]
Hi, thanks for replying, I appreciate it. One more question i want to
check with you is the format of inputs. If i want to input my own data, do
i need to transfer the data to tfrecord?

**Comment by QiShanZhang** [comment]
hi, please help me. when i run #60 pip install midi-ddsp . i will get the error error: metadata-generation-failed

**Comment by lukewys** [comment]
Hi, could you give a more specific error message? Does this error happens
inside pip? It could be your python version is too high. We recommend using
python 3.7 or 3.8.

Best,

Qishan Zhang ***@***.***> 于2023年8月4日周五 04:43写道：

**Comment by xinshouchun** [comment]
Hello, could you help me? Error when I install midi-ddsp：
(py38) PS C:\Users\gzzd\lunwen\chamber-ensemble-generator-master> pip install midi-ddsp
Collecting midi-ddsp
  Using cached midi_ddsp-0.2.6-py3-none-any.whl (67 kB)
Collecting tensorflowjs<3.19 (from midi-ddsp)
  Using cached tensorflowjs-3.18.0-py3-none-any.whl (77 kB)
Collecting crepe<0.0.13 (from midi-ddsp)
  Using cached crepe-0.0.12.tar.gz (15 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [37 lines of output]
      C:\Users\gzzd\AppData\Local\Temp\pip-install-8n054s8i\crepe_05f9e4ff1ed248a6bbc0cc3585457110\setup.py:2: DeprecationWarning: the imp module is deprecated i
n favour of importlib; see the module's documentation for alternative uses
        import imp
      C:\Users\gzzd\AppData\Local\Temp\pip-install-8n054s8i\crepe_05f9e4ff1ed248a6bbc0cc3585457110\setup.py:6: DeprecationWarning: pkg_resources is deprecated as
 an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
        import pkg_resources
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\gzzd\AppData\Local\Temp\pip-install-8n054s8i\crepe_05f9e4ff1ed248a6bbc0cc3585457110\setup.py", line 30, in <module>
          urlretrieve(base_url + compressed_file, compressed_path)
        File "C:\Users\gzzd\anaconda3\envs\py38\lib\urllib\request.py", line 247, in urlretrieve
          with contextlib.closing(urlopen(url, data)) as fp:
        File "C:\Users\gzzd\anaconda3\envs\py38\lib\urllib\request.py", line 222, in urlopen
          return opener.open(url, data, timeout)
        File "C:\Users\gzzd\anaconda3\envs\py38\lib\urllib\request.py", line 525, in open
          response = self._open(req, data)
        File "C:\Users\gzzd\anaconda3\envs\py38\lib\urllib\request.py", line 542, in _open
          result = self._call_chain(self.handle_open, protocol, protocol +
        File "C:\Users\gzzd\anaconda3\envs\py38\lib\urllib\request.py", line 502, in _call_chain
          result = func(*args)
        File "C:\Users\gzzd\anaconda3\envs\py38\lib\urllib\request.py", line 1397, in https_open
          return self.do_open(http.client.HTTPSConnection, req,
        File "C:\Users\gzzd\anaconda3\envs\py38\lib\urllib\request.py", line 1358, in do_open
          r = h.getresponse()
        File "C:\Users\gzzd\anaconda3\envs\py38\lib\http\client.py", line 1348, in getresponse
        File "C:\Users\gzzd\anaconda3\envs\py38\lib\http\client.py", line 316, in begin
          version, status, reason = self._read_status()
        File "C:\Users\gzzd\anaconda3\envs\py38\lib\http\client.py", line 277, in _read_status
          line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
        File "C:\Users\gzzd\anaconda3\envs\py38\lib\socket.py", line 669, in readinto
          return self._sock.recv_into(b)
        File "C:\Users\gzzd\anaconda3\envs\py38\lib\ssl.py", line 1241, in recv_into
          return self.read(nbytes, buffer)
        File "C:\Users\gzzd\anaconda3\envs\py38\lib\ssl.py", line 1099, in read
          return self._sslobj.read(len, buffer)
      TimeoutError: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
      Downloading weight file model-tiny.h5.bz2 ...
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed
× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
